# Generated by Django 4.1.3 on 2022-11-30 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_alter_project_id_alter_todo_id"),
        ("todo", "0002_todo_deleted"),
    ]

    operations = []
